using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Item : MonoBehaviour
{
    public float speed = 5.0f;//—‰º‘¬“x
    // Update is called once per frame
    void Update()
    {
        transform.position -= transform.up * speed * Time.deltaTime;//‰º‚É—‚¿‚Ä‚­
    }
    void OnTriggerEnter(Collider collision)
    {
        if (collision.gameObject.CompareTag("Down"))
        {
            //‰º•ÇÚG‚µ‚½‚çÁ‚·
            Object.Destroy(this.gameObject);
        }
        if (collision.gameObject.CompareTag("Player"))
        {
            //ƒpƒhƒ‹ÚG‚µ‚½‚çÁ‚·
            Object.Destroy(this.gameObject);
        }
    }
}
